const CATEGORIES_API = import.meta.env.VITE_CATEGORIES_API
const SINGLE_PRODUCT_API = import.meta.env.VITE_SINGLE_PRODUCT_API
const POST_ORDERS_API = import.meta.env.VITE_POST_ORDERS_API

export { CATEGORIES_API, POST_ORDERS_API, SINGLE_PRODUCT_API }

